site_name: Documentação Urbanize

nav:
  - Início: index.md
  - Sprints:
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
    - Sprint 4: sprints/sprint-4.md
    - Sprint 5: sprints/sprint-5.md
    - Sprint 6: sprints/sprint-6.md
    - Sprint 7: sprints/sprint-7.md
    - Sprint 8: sprints/sprint-8.md
  - Projeto:
    - Arquitetura e Tecnologias: projects/arquitetura.md
    - Padronização:    # Novo link de navegação
      - Git: padronizacaoGit.md  # Primeiro arquivo
      - Issues: padronizacaoIssues.md  # Segundo arquivo                             
  - Sobre: about.md

theme:
  font:
    text: Roboto
  language: pt-BR
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.top
    - content.tabs.link

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt

