-- AlterTable
ALTER TABLE "Executor" ALTER COLUMN "codigo" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Repassador" ALTER COLUMN "codigo" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Tomador" ALTER COLUMN "codigo" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "Tipo" ADD CONSTRAINT "Tipo_idEixo_fkey" FOREIGN KEY ("idEixo") REFERENCES "Eixo"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
